### ISSUE TITLE
Does GPT4 vision have this ability? 

### ISSUE THREAD

**Issue by ahsin-s** [OthersideAI/self-operating-computer#104]
Here is a response from GPT4 when I try to prompt it though the chat interface. It doesn't seem to actually be parsing the grid on the image or attempting to interpolate where to place the cursor. It seems to be guessing based on training data over some form of documentation about browser layout. 

_Given the standard layout of a web browser and the typical position of the address bar at the top, to get to the address bar in Google Chrome, one would usually click near the top of the browser window. In this case, with the grid overlay indicating position percentages, the address bar would typically be around the "50%" mark on the 'x' axis and somewhere between "0%" to "10%" on the 'y' axis.

However, since I cannot directly interpret the image to provide precise coordinates due to the limitations of my current capabilities, the description provided will be an estimate. If you need the exact coordinates, you would measure from the top of the browser window to the address bar and then calculate the percentage that this represents of the overall screen height.

Assuming the address bar is at the standard position, the response would be:

CLICK {{ "x": "50%", "y": "5%", "description": "Click: Chrome Address Bar", "reason": "To enter a URL and navigate to a website" }}

This is based on a common browser layout and not the specific image, as I cannot process the image to give precise coordinates._

**Comment by joshbickett** [comment]
> This is based on a common browser layout and not the specific image, as I cannot process the image to give precise coordinates._

It should be possible to get the x & y percent by taking the x & y pixel dimensions of the overall `.png` file and then measuring how many pixels the address bar is by using a tool like the screen grab with MAC (COMMAND+SHIFT+4). 

It is a little tricky but there are ways I think. You can get the screenshot in the project directory at each step. It does override `screenshot.png` so you may need to pause or stop the Self-Operating Computer. Sorry if this doesn't exactly answer the question. If you'd like to have more discussion with the community about what you're trying to do you can also go to our [Discord](https://discord.gg/YqaKtyBEzM). 

I'll close this issue for now, let us know if you have issues in the future.
