### ISSUE TITLE
Error parsing JSON: X get_image failed: error 8 (73, 0, 975)

### ISSUE THREAD

**Issue by bharath-dc** [OthersideAI/self-operating-computer#106]
![self-error](https://github.com/OthersideAI/self-operating-computer/assets/149763884/3e07aa0b-2119-47ef-a81c-ddb4d9def376)

I'm getting this error irrespective of the prompt that i put in. Please help me with it

**Comment by michaelhhogue** [comment]
@bharath-dc Do you have multiple monitors connected?

**Comment by bharath-dc** [comment]
nope i just have one connected, its the laptop's inbuilt one

**Comment by michaelhhogue** [comment]
@bharath-dc Is your system using Xorg or Wayland? Wayland isn't currently supported.

**Comment by bharath-dc** [comment]
ohh okay its using wayland, ill switch to xorg and try it. Thank you for the help!

**Comment by michaelhhogue** [comment]
@bharath-dc No problem! Let me know if that still didn't resolve the error.
