### ISSUE TITLE
Request: Add Issue Templates

### ISSUE THREAD

**Issue by Yash-1511** [OthersideAI/self-operating-computer#120]
**Feature Request**

**Description:**
I would like to suggest adding issue templates to the .github folder in the project repository. Issue templates can help streamline the issue creation process by providing a standardized format for bug reports and feature requests.

**Benefits:**
- Improve issue clarity and completeness.
- Encourage users to provide necessary information.
- Save time for both contributors and maintainers.

**Suggested Changes:**
Please consider adding the following two templates to the .github folder:
1. `bug_report.md` for reporting bugs.
2. `feature_request.md` for requesting new features.

**Example Usage:**
By implementing these templates, contributors can select the appropriate template when creating an issue, ensuring that relevant details are included, making it easier for maintainers to understand and address the issue.

**Contribution:** 
I am willing to contribute to this request by submitting a pull request (PR) to add the necessary issue templates. Please let me know if you would like me to proceed with this implementation.

I believe this enhancement would benefit the project and its community. Thank you for considering this request.

**Comment by joshbickett** [comment]
@Yash-1511 sounds like it shows up in the issue creating UI so that contributors can easily select options. Sounds good to me, interested to see a PR!

**Comment by Yash-1511** [comment]
> Contributor

Yes @joshbickett it shows up some instruction or pre templates for creating bug issues, feature request issues or pull request so it can be easy for both contributors and authors to understand it clearly. I have created PR #121 just check this out and give me your feedback.
