### ISSUE TITLE
`monitor_size` is hardcoded

### ISSUE THREAD

**Issue by outday29** [OthersideAI/self-operating-computer#122]
Hello, thanks for sharing this awesome project!

I noticed that in `config/settings.py`. The monitor size is hardcoded as:

```python
{
     "width": 1920,
     "height": 1080,
 }
```

Is that intentional? I figured out that you can get the monitor size using `pyautogui.size()`.

**Comment by michaelhhogue** [comment]
@outday29 It is automatically detected later when a screenshot is being captured. This value is simply a default that was added with accurate mode and should probably be removed
