### ISSUE TITLE
Where do i edit front end of it?

### ISSUE THREAD

**Issue by theexpeert** [OthersideAI/self-operating-computer#131]
How and WHERE can i edit the front end of it to make it much prettier.
and also in which folder do i edit it

**Comment by Yash-1511** [comment]
Hey @theexpeert Are you talking about the green screen?

**Comment by theexpeert** [comment]
Yes and also the buttons of it

**Comment by michaelhhogue** [comment]
@theexpeert `operate/dialog.py` in `main`. Be sure to run `pip install .` again after making any changes.

**Comment by theexpeert** [comment]
Ok ohk thank you sooo much

**Comment by theexpeert** [comment]
Do you have any idea how can I make an voice prompt output?

**Comment by michaelhhogue** [comment]
@theexpeert Do you mean prompting the operator using your voice? If so, you can use `--voice` mode. More info about `--voice` mode is in the README. 

Going ahead and closing this since I assume your initial question was resolved.
