### ISSUE TITLE
Can I convert it into gui? 

### ISSUE THREAD

**Issue by theexpeert** [OthersideAI/self-operating-computer#132]
We have to pass the commands on the terminal but can make a text box to do it and button which would be more easier for the person,  If yes then how ?

**Comment by michaelhhogue** [comment]
@theexpeert There are multiple approaches to creating GUIs in Python such as TKinter or PySide6 (Qt). However, I personally feel that a simple CLI is probably a better approach than a GUI at this time. Feel free to experiment with prompting the user via a GUI, though!

**Comment by theexpeert** [comment]
Oh ohk thanks , now imagine I coded then how do I make it so that the typing into a box connects to the same backend process like terminal one

**Comment by michaelhhogue** [comment]
@theexpeert I recommend studying the code-base, starting with `main` and following the different paths of execution. Once you captured user input via the GUI, you could pass that input to the model at the same point it's passed from the command line. Most of that happens in the `main` function itself. Hope that makes sense.

**Comment by theexpeert** [comment]
oh ohk thanks will try my best
