### ISSUE TITLE
'source' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by theexpeert** [OthersideAI/self-operating-computer#133]
'source' is not recognized as an internal or external command,
operable program or batch file.

![Screenshot (111)](https://github.com/OthersideAI/self-operating-computer/assets/155235981/df756526-17a4-480b-9a04-c790a9be415d)

**Comment by theexpeert** [comment]
is there any problem in creating a python virtual enviroment?

**Comment by theexpeert** [comment]
how do i fix this

**Comment by michaelhhogue** [comment]
@theexpeert Since you're on Windows, you need to run `.\venv\Scripts\activate` instead.

**Comment by theexpeert** [comment]
thanks

**Comment by hanantabak2** [comment]
use .venv\Scripts\activate instead of you're on Windows
