### ISSUE TITLE
[BUG] Gemini Pro - NO API Configuration

### ISSUE THREAD

**Issue by michsiu** [OthersideAI/self-operating-computer#138]
Found a bug? Please fill out the sections below. 👍

There should be a API configuration for Gemini Pro "apis" file

### Describe the bug

On the official doc, there should be a API configuration for Gemini Pro before run Gemini, like this
```
GOOGLE_API_KEY=userdata.get('GOOGLE_API_KEY')
genai.configure(api_key=GOOGLE_API_KEY)
```
![image](https://github.com/OthersideAI/self-operating-computer/assets/18113569/55437904-472b-4e8e-9d53-0a5229f9f575)

But there is no this step on the self-operating-computer
![image](https://github.com/OthersideAI/self-operating-computer/assets/18113569/807c78c9-c95a-4fc9-8131-a339d7ee503d)
After added the API configuration, it works now
### Another Bug About API Configuration
As I searched on google generativeai issue on GitHUb, it notes that it would be better add `transport='rest'` on API configuration of Gemini Pro
So, the correct code should be 
`genai.configure(api_key=YOUR_GOOGLE_API_KEY,transport='rest')`

**Comment by sangeet000007** [comment]
can it run completely without openai api key?
i added 
GOOGLE_API_KEY=userdata.get('GOOGLE_API_KEY')
genai.configure(api_key=GOOGLE_API_KEY,transport='rest')
but its still asked to set open ai key after setting null api key it enter into the software but returns "Gemini Invalid model"
should i add authorize credentials for a desktop application and i followed all the steps and got the json file but i dont know where to set those credentials and there is no tutorial in readme so kindly any one provide proper tutorial to work with gemini only.

**Comment by joshbickett** [comment]
@michsiu I can confirm that this `.configure` appears to fix the issue. I am working on a [branch](https://github.com/OthersideAI/self-operating-computer/tree/fix-config) to fix this and will merged once ready

**Comment by joshbickett** [comment]
@sangeet000007 you should be able to run the `gemini-pro-vision` model without an OpenAI key saved. You'll only need a Google key. I just fixed some issues with the `config` of these keys. I think it should be working correctly. Let me know if you have any issues

**Comment by joshbickett** [comment]
@michsiu I added `genai.configure(api_key=GOOGLE_API_KEY)` as you suggested and it appears that `gemini-pro-vision` is now working as expected. Could you try the newest version and let me know if it works for you?

**Comment by sangeet000007** [comment]
still asking for openai key and if i set inavlid key it enters but if you give commant it returns "[Error] -> Model not recognized : gemini-pro-vision" i tried both main branch and fix-config branch and give proper guide to input json file obtained for api from google and mainly api key is not asking while running operate as you shown in image.

**Comment by sangeet000007** [comment]
its working 
the click of button is not quite good with gemini it cant even send mails i suggest to improve gemini models with techniques like  Set-of-Mark Prompting gpt-4 and also give support for open source models
Thank you.

**Comment by michsiu** [comment]
Thanks @joshbickett ,it works
