### ISSUE TITLE
Operation with Chinese Input

### ISSUE THREAD

**Issue by michsiu** [OthersideAI/self-operating-computer#139]
Found a bug? Please fill out the sections below. 👍

It would be better to make a transformation of input from Chinese to English

### Describe the bug

Before the transformation, when I want to open chrome, it press "win" + r and input chrome, and press enter
But this just finish the input not really open the chrome

![image](https://github.com/OthersideAI/self-operating-computer/assets/18113569/48dfc817-d93f-4b4d-8d26-acc6176f59ea)

So, it would be better to tranfer Chinese input toEnglish Input

**Comment by Yash-1511** [comment]
Hey @michsiu ,

I saw that in search the text is not proper so the program can't open it. yeah that should be a bug or wrong response from LLM. but i think you need to run again. and also if possible please send your prompt also. 

also can you explain more about what is the transfer chinese input to english input

**Comment by michsiu** [comment]
Hello @Yash-1511 

please allow me to describe an example to understand it

If I want to open Google Chrome, normally, the AI will press "G" "o" "o" "l" "e" "Space" "C" "h" "r" "o" "m" "e" "Enter"

It works if the Input Method Engine is English

But when the Input Method Engine is Chinese, when you press space, it just finish input "google" on search bar, and the same to "Enter" key.

That is to say, when we press "Enter" key, it just finish input "googlechrome" rather than open the browser

So, if we want to open the google chrome, for Chinese Input Method Engine, it needs press "Enter" key twice, the first for finish input, second for open it

So if we want to use the program, we need to transfer from Chinese Input Method Engine to English Input Method Engine

Hope I have addressed it clearly, if you need more information, please let me know

**Comment by Yash-1511** [comment]
@michsiu You address the problem correctly. The problem is in the input method engine which you stated but currently it supports only English input method. actually we need to look to other engines also how they gonna work and what their methodology. for right now your solution is to transfer your chinese input method to english input method engine

**Comment by michsiu** [comment]
@Yash-1511 thanks
