### ISSUE TITLE
Clean up the github repo

### ISSUE THREAD

**Issue by justindhillon** [OthersideAI/self-operating-computer#15]
# There are some ways you can make this github repo look nicer. Press the gear icon in the about section:
![Screenshot from 2023-11-29 11-18-07](https://github.com/OthersideAI/self-operating-computer/assets/145078271/a61cc714-bb04-42dc-b86c-c8121eacb8b6)

## Right now it looks like this:
![Screenshot from 2023-11-29 11-17-56](https://github.com/OthersideAI/self-operating-computer/assets/145078271/db99e619-d3ce-4b12-a429-77c1b11bef9b)

## Lets add a discription, and remove the checkmarks because we don't have packages or deployments yet. We can always change this. We can also add tags.
![Screenshot from 2023-11-29 11-18-39](https://github.com/OthersideAI/self-operating-computer/assets/145078271/6784e45d-b1ca-42d3-899c-2897fdc104e0)

## Before:
![Screenshot from 2023-11-29 11-21-04](https://github.com/OthersideAI/self-operating-computer/assets/145078271/aa6a5b94-1691-4ad5-a80d-3c11bee2e716)

## After:
![Screenshot from 2023-11-29 11-20-49](https://github.com/OthersideAI/self-operating-computer/assets/145078271/64de4e31-e788-4760-ba8b-67b3046f0b48)

**Comment by joshbickett** [comment]
@justindhillon appreciate you flagging this. I went ahead and made the recommended changes, except website because we don't have a specific one for this project at this time. 

Appreciate additional tickets if you notice anything else, thanks!
