### ISSUE TITLE
[BUG] Model not recognized : gpt-4-with-ocr

### ISSUE THREAD

**Issue by willcray** [OthersideAI/self-operating-computer#150]
### Describe the bug

Hello, I'm unable to use either OCR or SOM mode. I receive the error `[Error] -> Model not recognized : gpt-4-with-<type run>`

### Steps to Reproduce

1. Run `operate -m operate -m gpt-4-with-ocr`
2. Prompt the model
3. Receive error

### Expected Behavior
I expect the model to work. It works when I don't pass an -m flag and select a mode. It works with just `operate`.

### Actual Behavior:
what actually happened.

### Environment
- OS: MacOS
- Model Used (e.g., GPT-4v, Gemini Pro Vision): GPT-4v
- Framework Version (optional): v1.2.8

**Comment by joshbickett** [comment]
Hi @willcray can you try running `pip show self-operating-computer` to confirm you are on `1.2.8`? It should look something like this. 
```
(venv) user@computername self-operating-computer % pip show self-operating-computer
Name: self-operating-computer
Version: 1.2.8
```

**Comment by willcray** [comment]
> Hi @willcray can you try running `pip show self-operating-computer` to confirm you are on `1.2.8`? It should look something like this.
> 
> ```
> (venv) user@computername self-operating-computer % pip show self-operating-computer
> Name: self-operating-computer
> Version: 1.2.8
> ```

@joshbickett this checked showed I was not running 1.2.8. I had the tag checked out, but I needed to run `pip install -v .`

**Comment by joshbickett** [comment]
If you update `self-operating-computer` to `1.2.8` then I think it may work
