### ISSUE TITLE
[BUG] Fedora system ,can't use it

### ISSUE THREAD

**Issue by Lori-Lin7** [OthersideAI/self-operating-computer#151]
Found a bug? Please fill out the sections below. 👍
![image](https://github.com/OthersideAI/self-operating-computer/assets/152047441/b783d5b0-0509-4452-8261-b86b9cf85e9e)
My system Fedora 39

### Describe the bug
i can't use 

Name: self-operating-computer
Version: 1.2.8
Summary: 
Home-page: 
Author: 
Author-email: 
License: 
Location: /home/linlori/self-operating-computer/venv/lib64/python3.12/site-packages
Requires: aiohttp, annotated-types, anyio, certifi, charset-normalizer, colorama, contourpy, cycler, distro, easyocr, EasyProcess, entrypoint2, exceptiongroup, fonttools, google-generativeai, h11, httpcore, httpx, idna, importlib-resources, kiwisolver, matplotlib, MouseInfo, mss, numpy, openai, packaging, Pillow, prompt-toolkit, PyAutoGUI, pydantic, pydantic-core, PyGetWindow, PyMsgBox, pyparsing, pyperclip, PyRect, pyscreenshot, PyScreeze, python-dateutil, python-dotenv, python3-xlib, pytweening, requests, rubicon-objc, six, sniffio, tqdm, typing-extensions, ultralytics, urllib3, wcwidth, zipp
Required-by: 

### Steps to Reproduce

1. went to "open the browser".
2. error as .
[Self-Operating Computer][Error] Something went wrong. Trying another method  X get_image failed: error 8 (73, 0, 1028)
[Self-Operating Computer][Error] Something went wrong. Trying again  X get_image failed: error 8 (73, 0, 1028)
[Self-Operating Computer][Error] -> cannot access local variable 'content' where it is not associated with a value 

3. not working

### Expected Behavior
A brief description of what you expected to happen.

### Actual Behavior:
what actually happened.

### Environment
- OS:  fedora 39
-  GPT-4v:
- Framework Version (optional):

**Comment by ghnnshymm** [comment]
which screenshot tool you use??

**Comment by michaelhhogue** [comment]
@Lori-Lin7 Try using X Server instead of Wayland. Wayland isn't supported at the moment.

**Comment by Lori-Lin7** [comment]
thank you ^^"
