### ISSUE TITLE
[BUG] WINDOWS install not finding gpt-4-with-ocr

### ISSUE THREAD

**Issue by peterthrees** [OthersideAI/self-operating-computer#166]
Hi,

Update 2024-02-25: 
===========================
It works now, but a subscription to chatgpt4 is not enough.
You also NEED to buy credits from chatgpt4, i bought credits for 5$ to test it because every api call will cost you something.
It's not cheap if you want to use it a lot.  I tried a few test and I'm alsmost at 1$. 
I hope there will be some alternatives later that are much cheaper or open source to do this.
Also it can't work with MS dos navigation. It does some weard things like cd c/\git\pong\ for example

===========================
Update: 
==================
 I created a new key and receiving an other error:
```
[Self-Operating Computer][gpt-4-with-ocr] That did not work. Trying another method
[Self-Operating Computer][Operate] That did not work. Trying again  Error code: 404 - {'error': {'message': 'The model `gpt-4-vision-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
[Self-Operating Computer][Error] -> cannot access local variable 'content' where it is not associated with a value
```

Previous:
==================
I get this error:
```
[Self-Operating Computer][gpt-4-with-ocr] That did not work. Trying another method
[Self-Operating Computer][Operate] That did not work. Trying again  Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-dT0tN***************************************3YFi. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
[Self-Operating Computer][Error] -> cannot access local variable 'content' where it is not associated with a value
```

I have chatgpt4, the key is correct and has access set to all.
What could be the reason? 

![image](https://github.com/OthersideAI/self-operating-computer/assets/2140969/0537b1d0-543d-43bb-87d0-cd3fed21389f)

Kr,
Peter

**Comment by peterthrees** [comment]
![Screenshot 2024-02-17 224534](https://github.com/OthersideAI/self-operating-computer/assets/2140969/a51dfd3b-643d-465f-871d-10fd2df4546f)

**Comment by peterthrees** [comment]
I tried the latest on another computer, but I'm getting the same message.

**Comment by michaelhhogue** [comment]
@peterthrees Have you spent at least $5 on API credits? See the bottom of the README for more info. People typically get that error when they haven't yet spent the required $5 to gain access to GPT-4 Vision.

**Comment by peterthrees** [comment]
@michaelhhogue  Thanks, that was indeed the issue.
Maybe it is explained somewhere in this git rpo and I have missed it? But I thought the Api key and subscription was sufficient.
If the feedback is from chatgpt, they should maybe provide feedback with the correct error like, "not enough credits".

**Comment by EdenIsHereToStay** [comment]
> It works now, but a subscription to chatgpt4 is not enough.
> You also NEED to buy credits from chatgpt4, i bought credits for 5$ to test it because every api call will cost you something.
> It's not cheap if you want to use it a lot. I tried a few test and I'm alsmost at 1$.
> I hope there will be some alternatives later that are much cheaper or open source to do this.
> Also it can't work with MS dos navigation. It does some weard things like cd c/\git\pong\ for example

What do you mean paid for credits? I currently have 21.95 in credit in my API account... does that count? I'm having the same error meesage on both computers I've attempted installation on:
```
[Self-Operating Computer | gpt-4-with-ocr]
Hello, I can help you with anything. What would you like done?
[User]
test
[Self-Operating Computer][gpt-4-with-ocr] That did not work. Trying another method
[Self-Operating Computer][Operate] That did not work. Trying again  Error code: 404 - {'error': {'message': 'The model `gpt-4-vision-preview` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
[Self-Operating Computer][Error] -> local variable 'content' referenced before assignment

C:\Users\eddie\Ai Tools>
```
