### ISSUE TITLE
[BUG] Not running on Ubuntu 22.04.4 LTS

### ISSUE THREAD

**Issue by BurnyCoder** [OthersideAI/self-operating-computer#168]
### Describe the bug

I just installed the self-operating computer on Ubuntu and got an error when running it: [gpt-4-with-ocr] That did not work. Trying another method, [Operate] That did not work. Trying again  X get_image failed: error 8 (73, 0, 966), [Error] -> local variable 'content' referenced before assignment 

### Steps to Reproduce

Both pip and git cloning installations. 

### Expected Behavior

Normal functioning.

### Actual Behavior:

[Self-Operating Computer | gpt-4-with-ocr]
Hello, I can help you with anything. What would you like done?
[User]
go to google docs
[Self-Operating Computer][gpt-4-with-ocr] That did not work. Trying another method 
[Self-Operating Computer][Operate] That did not work. Trying again  X get_image failed: error 8 (73, 0, 966)
[Self-Operating Computer][Error] -> local variable 'content' referenced before assignment 

### Environment
- OS: Ubuntu 22.04.4 LTS
- Model Used: GPT-4v

### Thoughts

Could the issue be permissions as I'm not on mac?

**Comment by joshbickett** [comment]
@BurnyCoder do you have Wayland enabled? Check out this ticket I think it is related #80

**Comment by BurnyCoder** [comment]
That fixed it, thanks!

**Comment by joshbickett** [comment]
Ok, closing!
