### ISSUE TITLE
OpenAI Message: "can't assist with navigating or interacting with software on a computer in real-time..."

### ISSUE THREAD

**Issue by jaseva** [OthersideAI/self-operating-computer#17]
Is anyone else receiving this message?

<img width="1084" alt="image" src="https://github.com/OthersideAI/self-operating-computer/assets/5480431/bcd05dc4-d08b-438f-9a9d-3888f1e754f5">

**Comment by michaelhhogue** [comment]
I have on very rare occasions gotten a response like this. The prompt may just need to be further refined to explain that it is able to interact with the user's operating system via its text responses.

**Comment by jaseva** [comment]
> I have on very rare occasions gotten a response like this. The prompt may just need to be further refined to explain that it is able to interact with the user's operating system via its text responses.

Thanks for the suggest. I added this line to the SUMMARY_PROMPT in the main.py file if anyone experiences OpenAI's policy restriction:

"You are able to interact with the user's operating system via received text input by the end-user."

That seemed to have resolved the frequent message I was receiving. Makes me realize the risk impact of OpenAI's policies on created GPT applications.
