### ISSUE TITLE
[Linux]: X get_image failed: error 8 (73, 0, 1316)  [Error] --> cannot access local variable 'content' where it is not associated with a value

### ISSUE THREAD

**Issue by OrdinaryCoffeeCup** [OthersideAI/self-operating-computer#183]
### Describe the bug

Got the captioned error running in Debian. Can any one help diagnose? Thanks!

**Comment by joshbickett** [comment]
@OrdinaryCoffeeCup do you have Wayland enabled? Check out this ticket I think it is related https://github.com/OthersideAI/self-operating-computer/issues/80

**Comment by OrdinaryCoffeeCup** [comment]
> @OrdinaryCoffeeCup do you have Wayland enabled? Check out this ticket I think it is related #80

Yes solved after disabling Wayland, thanks a lot!
