### ISSUE TITLE
Error during installation.

### ISSUE THREAD

**Issue by ElCuboNegro** [OthersideAI/self-operating-computer#2]
Collecting pyobjc-core==10.0 (from -r requirements.txt (line 32))
  Using cached pyobjc-core-10.0.tar.gz (921 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      running egg_info
      error: PyObjC requires macOS to build
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by ronnachum11** [comment]
This is an error on Windows due to Mac-specific dependencies. My PR fixes this, but you can do a temp fix by removing 

```
pyobjc-core==10.0
pyobjc-framework-Cocoa==10.0
pyobjc-framework-Quartz==10.0
```

from the requirements.txt.
