### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by Kreijstal** [OthersideAI/self-operating-computer#20]
I guess most people actually use windows, not macos

**Comment by rohanarun** [comment]
Our Atlas-1 model supports windows, and doesn't need to hard-code clicks so it will work on different screen resolutions and sizes as well. https://youtu.be/IQuBA7MvUas We're releasing Atlas-1 in the coming week

**Comment by 0xdevalias** [comment]
See also:

- https://github.com/OthersideAI/self-operating-computer/issues/32

**Comment by Tophness** [comment]
Not sure what is meant by this. It's used pyautogui from the start, which is windows-only.

**Comment by 0xdevalias** [comment]
> Not sure what is meant by this. It's used pyautogui from the start, which is windows-only.

@Tophness A quick google seems to suggest that's not true:

- https://pyautogui.readthedocs.io/en/latest/
  - > PyAutoGUI lets your Python scripts control the mouse and keyboard to automate interactions with other applications. The API is designed to be simple. **PyAutoGUI works on Windows, macOS, and Linux,** and runs on Python 2 and 3.

**Comment by michaelhhogue** [comment]
@TerminatedProcess I don't think anyone has tested on wsl2 yet. I'll try it out and see how it works.

**Comment by michaelhhogue** [comment]
@TerminatedProcess There appears to be some issues with it in WSL. If you're on windows, it's recommended that you go ahead and run the program from the host system. VMs are quite unpredictable with PyAutoGUI.

**Comment by TerminatedProcess** [comment]
Just for kinks, I'm trying this with a wsl2 ubuntu that has a desktop. Using this github [project](https://github.com/DesktopECHO/xWSL)..
