### ISSUE TITLE
This appears to be very similar to our Atlas-1 model, but with hard coded clicks. Is that correct?

### ISSUE THREAD

**Issue by rohanarun** [OthersideAI/self-operating-computer#21]
Hey guys we've been training a very similar multi-modal model called Atlas-1, however we don't need to hard-code click positions like it appears here, because we trained our model to find UI-elements directly and solve the hardest problems in automations. With the name Agent-1, it almost seems copied, but I hope that's not correct. 

We introduce the idea of "Semantic Targets" which understand the underlying intent of a target, and so it's robust to even future design changes. 

You can see in our tutorial published last month, we can also search google and much more because Atlas-1 doesn't need to hard code click positions https://youtu.be/IQuBA7MvUas?si=lSaFpH0WMIKRtYrU

**Comment by rohanarun** [comment]
![image](https://github.com/OthersideAI/self-operating-computer/assets/11659839/a88909f8-4c01-4dc2-8934-2eaf10e151c7)
In your code you can see click positions have to be hard-coded, which makes it hard to scale a design like this to every automation. This isn't necessary with our Atlas-1 model we're releasing in the coming week.

**Comment by Kreijstal** [comment]
> ![image](https://private-user-images.githubusercontent.com/11659839/286926485-a88909f8-4c01-4dc2-8934-2eaf10e151c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MTMwMzksIm5iZiI6MTcwMTQxMjczOSwicGF0aCI6Ii8xMTY1OTgzOS8yODY5MjY0ODUtYTg4OTA5ZjgtNGMwMS00ZGMyLTg5MzQtMmVhZjEwZTE1MWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA2Mzg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ZjYxMmI2OGU5Y2IwOWNlNTVhZGQ1ZTcwODE4OTFlMDI1ODA4MWQxYzc0Y2Q3NmU3YWQ5ZTFiMTAyOGIwMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aVrt4i27H24SlMYNTVe74iS1nndU6ZJY1OUoQWDvCSc) In your code you can see click positions have to be hard-coded, which makes it hard to scale a design like this to every automation. This isn't necessary with our Atlas-1 model we're releasing in the coming week.

is this an open source model?

**Comment by rohanarun** [comment]
Re-opening @michaelhhogue are you an official contributor to this project? Could you comment on where the name Agent-1 came from? This appears to have blatantly ripped of the work of researchers working hard over a year. 

Any open source contributors should consider that this firm raised millions and is scamming open source devs into stealing work for them. They never responded to our claims they stole this work, even down to the name agent-1, which is incredibly shameful if true and our attorneys would love to hear from an official contributor. 

We will be publishing our solution open source as well, and it actually works.
