### ISSUE TITLE
Question: How to Train YOLO?

### ISSUE THREAD

**Issue by daichisaito-cs** [OthersideAI/self-operating-computer#212]
Could you clarify how you trained YOLO to obtain the weight file `best.pt`? Is this a pre-existing checkpoint, or did you train the model yourself?

I'm planning to train YOLO using a new dataset, so I'd appreciate any details you could provide on the training process. Thank you!

**Comment by joshbickett** [comment]
@daichisaito-cs I trained the model myself based on a dataset I built up from my own use. I created the dataset by getting the bounding box data from web elements in a web browser.

**Comment by humanely** [comment]
Since YOLO is AGPL, how is this project MIT Licensed?
