### ISSUE TITLE
Bug Report: Issue with Correcting API Key in self-operating-computer After Incomplete Input

### ISSUE THREAD

**Issue by kirushake** [OthersideAI/self-operating-computer#215]
I encountered an issue while using the self-operating-computer package. When running the operate command, the prompt to input the API key appeared. Unfortunately, I accidentally entered an incomplete API key. Now, I am unable to correct this mistake, as there is no clear instruction on how to reset or update the API key after an incorrect input.

Steps to Reproduce:

Install the self-operating-computer package as per the documentation.
Run the operate command.
When prompted to input the API key, enter an incomplete or incorrect key.
Attempt to correct or re-enter the API key, but there is no available option to do so.
Expected Behavior: There should be a clear way to reset, update, or correct the API key if entered incorrectly during the initial prompt.

Actual Behavior: Once the incomplete API key is entered, I cannot find a way to re-enter or reset the key, causing the system to not function as expected.

Environment:

OS: Window 11
Python version: 3.12

Add a clear option to re-enter the API key upon detecting an invalid or incomplete key.
Provide documentation on how to manually update the stored API key after the initial input.
Thank you for looking into this issue!

**Comment by Tybost** [comment]
The same thing happened to me and there was no command I could figure out to fix the issue. I happened upon the .env file out in the open of my C:\Users\PCNAME and inside of it was a simple line 'OPENAI_API_KEY=' with my broken key attached. Just needed to copy and paste the new one in and it started working.

**Find the .env file to fix the issue.** I installed this through Anaconda and perhaps that's just where it drops files.
