### ISSUE TITLE
[BUG]  X get_image failed: error 8 (73, 0, 1272)

### ISSUE THREAD

**Issue by Dafan-sxd** [OthersideAI/self-operating-computer#217]
Found a bug? Please fill out the sections below. 👍

### Describe the bug

When i enter command operate and then i entered the openAI's API KEY and then when i enter the work it gives me an error like 

[Self-Operating Computer | gpt-4-with-ocr]
Hello, I can help you with anything. What would you like done?
[User]
open notepad
[Self-Operating Computer][gpt-4-with-ocr] That did not work. Trying another method
[Self-Operating Computer][Operate] That did not work. Trying again  X get_image failed: error 8 (73, 0, 1272)
[Self-Operating Computer][Error] -> local variable 'content' referenced before assignment

### Steps to Reproduce

1. operate
2. enter openai's api key
3. [Self-Operating Computer | gpt-4-with-ocr]
    Hello, I can help you with anything. What would you like done?
    [User]
   open notepad
4. It gives me this error
    [Self-Operating Computer][gpt-4-with-ocr] That did not work. Trying another method
    [Self-Operating Computer][Operate] That did not work. Trying again  X get_image failed: error 8 (73, 0, 1272)
    [Self-Operating Computer][Error] -> local variable 'content' referenced before assignment

### Expected Behavior
Notepad should be opened

### Actual Behavior:
Throwing an error

### Environment
- OS: Ubuntu
- Model Used (e.g., GPT-4v, Gemini Pro Vision):
- Framework Version (optional):

**Comment by duboweidong** [comment]
I also encountered the same problem, have you solved it

**Comment by joshbickett** [comment]
@Dafan-sxd @duboweidong do you have Wayland enabled, check out ticket https://github.com/OthersideAI/self-operating-computer/issues/80 related to this.
