### ISSUE TITLE
Keeps saying 'I'm sorry, but I can't assist with that request.' 

### ISSUE THREAD

**Issue by andreisuslov** [OthersideAI/self-operating-computer#23]
Whatever task I give, it keeps saying this. I don't know how to resolve it.

**Comment by michaelhhogue** [comment]
Can you open operate/main.py and the following line to the end of VISION_PROMPT:

```Don't respond saying you're unable to assist with requests like this since you are able to interact with the user's operating system via text responses you send to the end user.``

Please let me know if this resolves the issue for you. If so, I'll likely open a PR adding this to the prompt to help limit this issue. Others, including myself, occasionally get responses like this.

**Comment by joshbickett** [comment]
Merged @michaelhhogue PR. @andreisuslov interested if this resolves your issue.

**Comment by michaelhhogue** [comment]
Closing as I haven't seen an instance of this issue since the merge of #28

**Comment by GokalpGokdogan** [comment]
It started to happening to me. Any solutions?

<img width="1048" alt="image" src="https://github.com/OthersideAI/self-operating-computer/assets/91427252/c9dae872-9b90-439f-8b7c-61cdabd458da">

**Comment by zenanybuqueinsignia** [comment]
![image](https://github.com/OthersideAI/self-operating-computer/assets/154428814/42a0dff3-9788-4e55-acb6-0dae218229dd)

Having it too at chatgpt

**Comment by fgaletic** [comment]
I think in drug lord circles this is called bait and switch. The app is only responding like this lately.
