### ISSUE TITLE
Enhancing Safety: User Confirmation for Command Execution

### ISSUE THREAD

**Issue by haseeb-heaven** [OthersideAI/self-operating-computer#25]
Feature Request:

1. **Enhanced Security Confirmation**
    - **Issue:** Add security on user prompts for executing potentially dangerous commands.
    - **Description:** Implement a robust security feature that ensures user confirmation before executing any potentially harmful actions.
    - **Plan:** 
        - Create a user-friendly dialog box that prompts for confirmation.
        - Allow users to configure settings to override this security feature if needed.
        - Implement this security layer in the codebase to prevent unintended actions.

**Comment by joshbickett** [comment]
@haseeb-heaven this makes a lot of sense to me. It'd be great to get a PR for this. At the least, would you be able to add this to [Contributing.md](https://github.com/OthersideAI/self-operating-computer/blob/main/CONTRIBUTING.md) in the "Contribution Ideas" section for other's to work on?

**Comment by haseeb-heaven** [comment]
> @haseeb-heaven this makes a lot of sense to me. It'd be great to get a PR for this. At the least, would you be able to add this to [Contributing.md](https://github.com/OthersideAI/self-operating-computer/blob/main/CONTRIBUTING.md) in the "Contribution Ideas" section for other's to work on?

Sure i will add this there.

**Comment by haseeb-heaven** [comment]
Here is the [PR for this](https://github.com/OthersideAI/self-operating-computer/pull/114) @joshbickett

**Comment by joshbickett** [comment]
@haseeb-heaven thanks again for the PR. I'll go ahead and close this issue now that we have this tracked in `contributing.md`

**Comment by yogeshwaranEvil** [comment]
hey hi , I am going to try the implementation of hugging face. please comment below is it possible any idea about it and i am new to this.
