### ISSUE TITLE
OpenAI API error: The model `gpt-4-vision-preview` does not exist or you do not have access to it.

### ISSUE THREAD

**Issue by fschuindt** [OthersideAI/self-operating-computer#26]
Complete log:
```
[Self-Operating Computer]
Hello, I can help you with anything. What would you like done?
[User]
Open the Google Photos inside the Google Chrome
Error parsing JSON: Error code: 404 - {'error': {'message': 'The model `gpt-4-vision-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
[Self-Operating Computer][Error] something went wrong :(
[Self-Operating Computer][Error] AI response
Failed take action after looking at the screenshot
(venv) syzygy@Syzygys-MacBook-Pro self-operating-computer %
```

I have the GPT-4 since it launched, I also can use my keys with other tools like `sgpt`, but appears that for some reason my account is lacking this model, any ideas? I have tried the suggested URL, but isn't much there.

**Comment by michaelhhogue** [comment]
Have you spent a minimum of $5 in OpenAI API credits? Once you've spent at least $5, you'll move into Tier 1 access which gives you access to gpt-4-vision-preview.

**Comment by fschuindt** [comment]
@michaelhhogue Thanks for replying.

Ah, I got it wrong when I first read it, I thought it were about having sent them money already (in general), which I do every month.

I have added 10 USD to my account as prepaid credit. But it stills gives out the same error. I'm going to test again later and report back here.

**Comment by michaelhhogue** [comment]
@fschuindt Yeah it can take a little bit to update in the system. Hope it works out!

**Comment by fschuindt** [comment]
@michaelhhogue It's working, thank you!!

**Comment by CarloAguirre** [comment]
hi, how u fix it? thanks.
