### ISSUE TITLE
Error parsing JSON: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

### ISSUE THREAD

**Issue by namas191297** [OthersideAI/self-operating-computer#29]
I have everything set up correctly, added 5$ worth credit to my OpenAI account but I still keep getting this error. I don't believe I have exceeded my current quota, could someone shed some light on this? Thanks.

**Comment by shubhexists** [comment]
This does not seem to be an error from this repository. Kindly check your OpenAI account if it actually shows the credits... If yes, then you may try generating a new key

**Comment by joshbickett** [comment]
Hi, this looks like an `openai` rate limit so I'll go ahead and close this issue.
