### ISSUE TITLE
Add a grid of coordinates

### ISSUE THREAD

**Issue by Kreijstal** [OthersideAI/self-operating-computer#31]
Since it likes to misclicks a lot, you could either train a model to do image segmentation or, you can with clever prompt engineering add a barebones grid asking to solve the puzzle, "in which coordinate can the search button be found" this should make it more robust, right?

**Comment by 0xdevalias** [comment]
See also:

- https://github.com/OthersideAI/self-operating-computer/issues/3

**Comment by Daisuke134** [comment]
How about applying a dynamic grid approach to enhance click accuracy?

For example, we could adjust the grid density based on the proximity to the cursor. The areas closer to the cursor would have a denser grid, allowing for more accurate click predictions.
