### ISSUE TITLE
Feature: Ollama Support

### ISSUE THREAD

**Issue by orkutmuratyilmaz** [OthersideAI/self-operating-computer#35]
Hello and thanks for this beautiful repo.

Would you consider adding open source model support, especially with [Ollama](https://ollama.ai/)?

Best,
Orkut

**Comment by joshbickett** [comment]
@orkutmuratyilmaz I believe @michaelhhogue is working on this now. Since we have another issue #86 to track this same update I'll close this issue for now. Join our [discord](https://discord.gg/YqaKtyBEzM) where we can talk about this and more.
