### ISSUE TITLE
Seek for cooperation and solution sharing

### ISSUE THREAD

**Issue by James4Ever0** [OthersideAI/self-operating-computer#37]
I have been researching in automotive computers for years.

Topics that you might be interested in that I have dug into:

- [Free Energy Principle & Active Inference](https://github.com/BerenMillidge/FEP_Active_Inference_Papers)
- [LLM Robotics](https://github.com/GT-RIPL/Awesome-LLM-Robotics)
- [Q-Star Learning](https://github.com/estill01/open_qstar)
- [RT-2](https://github.com/James4Ever0/agi_computer_control/tree/master/rt_x_experiments) & [RT-X dataset](https://robotics-transformer-x.github.io/)
- [Crop & Zoom Based Attention](https://github.com/James4Ever0/agi_computer_control/tree/master/rt_x_experiments/real_attention)
- [Recursive Positional Encoding](https://github.com/James4Ever0/agi_computer_control/blob/master/rt_x_experiments/real_attention/recursive_positional_encoding.py)
- [Dynamic Reservoir Computing](https://github.com/James4Ever0/agi_computer_control/tree/master/dynamic_plasticity_neural_networks)
- [Automotive Learning Rate](https://github.com/James4Ever0/agi_computer_control/tree/master/rt_x_experiments/gradient_undescent)
- [Hardware Mouse/Keyboard Control](https://github.com/James4Ever0/agi_computer_control/tree/master/hardware_capture_hid_power_control)
- [Physical Robot Based HID Control](https://github.com/James4Ever0/agi_computer_control/tree/master/lego_mindstorm_physical_mouse_keyboard_control)
- [Bit-level Autoregressive Transformer](https://github.com/James4Ever0/agi_computer_control/blob/master/rt_x_experiments/special_tokenizer_with_actions/test_hierachical_tokenization.py)
- [Browser-based AI Playground](https://github.com/James4Ever0/agi_computer_control/tree/master/the_frozen_forest_intro)
- [Containerized Console and GUI AI Playground](https://github.com/James4Ever0/agi_computer_control/tree/master/containerized_chatgpt_agent)

I have dedicated repositories that you may be interested into:

- [agi-computer-control](https://github.com/James4Ever0/agi_computer_control): automotive computer, which can see, hear and operate
- [metalazero](https://gitee.com/x00e0d991e368/metalazero): multi-platform computer automation attempts

Other similar projects that I am monitoring:

- [GPT-4V-Act](https://github.com/ddupont808/GPT-4V-Act)
- [SingularGPT](https://github.com/abhiprojectz/SingularGPT)
- [gpt-eyes](https://github.com/Charmve/gpt-eyes)
- [gpt4v-browsing](https://github.com/unconv/gpt4v-browsing)
- [self-operating-computer](https://github.com/OthersideAI/self-operating-computer)

Apologize for my unorganized code structure. I am trying to improve development experience by AI generated documentation & usage demonstration and client-side LLM & semantic search, which may solve this long-standing task among all my previous repositories.

**Comment by joshbickett** [comment]
Hi @James4Ever0, thanks for sharing the resources. I wanted to link to our [discord](https://discord.gg/YqaKtyBEzM) in case you want to share there as well. I'll close this issue for now. Thanks again!
