### ISSUE TITLE
Add support for speech recognition with a voice button

### ISSUE THREAD

**Issue by legendkartik45** [OthersideAI/self-operating-computer#38]
Can refer the below code sample

![image](https://github.com/OthersideAI/self-operating-computer/assets/92686157/d8ef19af-6510-4fb8-affa-1d522e6aacea)

**Comment by michaelhhogue** [comment]
Speech recognition using Whisper is being discussed in #52

**Comment by legendkartik45** [comment]
> Speech recognition using Whisper is being discussed in #52

Cool, closing this issue then.
