### ISSUE TITLE
operate issue

### ISSUE THREAD

**Issue by kannanspeed** [OthersideAI/self-operating-computer#42]
"Traceback (most recent call last):
  File "C:\Users\KANNAN\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\KANNAN\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\KANNAN\AppData\Local\Programs\Python\Python310\Scripts\operate.exe\__main__.py", line 4, in <module>
  File "C:\Users\KANNAN\AppData\Local\Programs\Python\Python310\lib\site-packages\operate\main.py", line 30, in <module>
    client = OpenAI()
  File "C:\Users\KANNAN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\_client.py", line 93, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable" while entering 'operate' I'm getting this error, anyone help me to solve this

**Comment by shubhexists** [comment]
add your OPEN_AI_KEY in the environment variables 
Or make a .env file with contents
`OPEN_AI_KEY = your_open_ai_key`

**Comment by kannanspeed** [comment]
now its worked,

"Error parsing JSON: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
[Self-Operating Computer][Error] something went wrong :(
[Self-Operating Computer][Error] AI response" now getting this one I have enough balance in my credits for use

**Comment by shubhexists** [comment]
Hi, This is a OpenAI error and has nothing to do with the code....
You may have a look at your openAI account once to see if you have the credit

Also references - https://community.openai.com/t/probable-openai-bug-insufficient-quota-error-on-paid-account-with-available-balance/331067

Maybe this might help

**Comment by kannanspeed** [comment]
nothing is working bro, I have enough credits even its not working

**Comment by kannanspeed** [comment]
![Screenshot (187)](https://github.com/OthersideAI/self-operating-computer/assets/47640609/a20ece65-3645-4ab7-b149-1d55dd174291)
open ai just got released an new update, actual issue is from there side

**Comment by joshbickett** [comment]
Looks like this is a `openai` issue, so I'll close this
