### ISSUE TITLE
Add downsampled images as context instead of screenshot.png?

### ISSUE THREAD

**Issue by klxu03** [OthersideAI/self-operating-computer#56]
Would it be advantageous to keep a collage of downsampled previous images, maybe to 160px x 90px and just stack them in a line left to right, one after another, and constantly pass this image as additional context for each action like here is a timeline of previous states the model has traversed through?

FYI: I would be happy to draft and code this feature out!

**Comment by shubhexists** [comment]
Out of curiosity, Doesn't the Vision model has any sort of "Token Limit" like it has in GPT4?

**Comment by klxu03** [comment]
Got it. I'll go draft up a PR for the previous image stacks! I'm planning on just making it an immediate previous message in pseudo_messages.

Also, regarding the token limit, correct me if I'm wrong, is the [GPT4V](https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo) context window up to 128k tokens? 
If so, would there be a real concern about hitting the token limit? With some [calculations](https://community.openai.com/t/how-do-i-calculate-image-tokens-in-gpt4-vision/492318/2), [where x = one dimension of maximum image size](https://www.wolframalpha.com/input?i2d=true&i=85+%2B+170Power%5B%5C%2840%29Divide%5Bx%2C512%5D%5C%2841%29%2C2%5D+%3D+128000) you get x = 14044, meaning you can pass up to a 14044px x 14044px image. To hit the token limit, you would need to pass a lot of images to hit 2 * 10^8 total pixels.

**Comment by klxu03** [comment]
Got it. I'll go draft up a PR for the previous image stacks! I'm planning on just making it an immediate previous message in pseudo_messages.

Also, regarding the token limit, correct me if I'm wrong, is the [GPT4V](https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo) context window up to 128k tokens? 
If so, would there be a real concern about hitting the token limit? With some [calculations](https://community.openai.com/t/how-do-i-calculate-image-tokens-in-gpt4-vision/492318/2), [where x = one dimension of maximum image size](https://www.wolframalpha.com/input?i2d=true&i=85+%2B+170Power%5B%5C%2840%29Divide%5Bx%2C512%5D%5C%2841%29%2C2%5D+%3D+128000) you get x = 14044, meaning you can pass up to a 14044px x 14044px image. To hit the token limit, you would need to pass a lot of images to hit 2 * 10^8 total pixels. 

@michaelhhogue @shubhexists

**Comment by michaelhhogue** [comment]
@klxu03 Can this be closed since #57 was merged?

**Comment by joshbickett** [comment]
closing since old and less relevant now
