### ISSUE TITLE
Proposal: Support for addition of tests using frameworks like Unittest, Pytest etc.

### ISSUE THREAD

**Issue by legendkartik45** [OthersideAI/self-operating-computer#65]

**Comment by rohanarun** [comment]
Warning: this project appears to have blatantly ripped off the work of researchers over a year on a new multi-modal model, Atlas-1, and is attempting to scam open source devs into doing that work https://github.com/OthersideAI/self-operating-computer/issues/67

**Comment by joshbickett** [comment]
I'm definitely interested in a way to automate testing. If someone makes a PR that'd be great!

**Comment by joshbickett** [comment]
We did get a PR that added `evaluate.py` so I'll close this now!
