### ISSUE TITLE
Warning: this project appears to have blatantly ripped off the work of researchers over a year on a new multi-modal model, Atlas-1, and is attempting to scam open source devs into doing that work

### ISSUE THREAD

**Issue by rohanarun** [OthersideAI/self-operating-computer#67]
Re-opening @michaelhhogue  are you an official contributor to this project? Could you comment on where the name Agent-1 came from? This appears to have blatantly ripped of the work of researchers working hard over a year.

Any open source contributors should consider that this firm raised millions and is scamming open source devs into stealing work for them. They never responded to our claims they stole this work, even down to the name agent-1, which is incredibly shameful if true and our attorneys would love to hear from an official contributor.

We will be publishing our solution open source as well, and here is Atlas-1, which we've been training for over a year and published last month: https://youtu.be/IQuBA7MvUas

What is Agent-1 and where did the name come from? It appears these guys blatantly ripped off our work and are now scamming open source devs into copying it for them.

**Comment by michaelhhogue** [comment]
@rohanarun I'm just an open-source contributor helping to triage issues. This framework provides in interface to GPT-4v from OpenAI, allowing it to in-directly control the computer via its text responses. If you have an issue with that isn't directly related to this repository, you need to contact the owner regarding your concerns rather than opening Issues and harassing other contributors. Thanks.

**Comment by rohanarun** [comment]
> @rohanarun I'm just an open-source contributor helping to triage issues. This framework provides in interface to GPT-4v from OpenAI, allowing it to indirectly control the computer via its text responses. If you have an issue with that isn't directly related to this repository, you need to contact the owner regarding your concerns rather than opening Issues and harassing other contributors. Thanks.

Wow, but what gives you the right to steal our work? That's incredible and this is pretty blatant. The owners don't seem to respond to the claims so we are warning open source devs not to get taken advantage of. If they stole our work before we even open sourced it, how do you think they treat open source developers?

**Comment by Bunger-Beesechurger** [comment]
![Screenshot (813)](https://github.com/OthersideAI/self-operating-computer/assets/124498059/b0a6bc1f-1c53-43bb-94cf-2c58dc457059)

@rohanarun 
I'm not a contributor to this github, just part of the audience usually, but this seems earlier than your thing. Early August is when this article came out, so it's been in the works even earlier than that. Stop spamming every issue

**Comment by rohanarun** [comment]
> ![Screenshot (813)](https://private-user-images.githubusercontent.com/124498059/287474619-b0a6bc1f-1c53-43bb-94cf-2c58dc457059.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NTExNzgsIm5iZiI6MTcwMTU1MDg3OCwicGF0aCI6Ii8xMjQ0OTgwNTkvMjg3NDc0NjE5LWIwYTZiYzFmLTFjNTMtNDNiYi05NGNmLTJjNThkYzQ1NzA1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMlQyMTAxMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTk3ZjNiMGUyZDc2ZjE3MjFlMTU5N2E4ZTgwNmM1NTRlNDgxZDAxMjEyNGM0MDQ0OWYxMmNkNjU4MGI0YTQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Y_qsMNvb5p4cvyltioPZzlgddpzCIzU4hRB5QCutSR8)
> 
> @rohanarun I'm not a contributor to this github, just part of the audience usually, but this seems earlier than your thing. Early August is when this article came out, so it's been in the works even earlier than that. Stop spamming every issue

Our project was started in July 2022 before the chatGPT API was released, including public publications which we freely gave out and we intend to open source. What's concerning is they continue to steal the work without attribution. It took a year to train our new multi-modal model, and we've been working on agents since this post in July  We've been working on this for over a year and we called them out on copying our launch in April as well, and our community has been aware of atlas-1: https://www.producthunt.com/products/cheat-layer#project-atlas-agents
https://www.producthunt.com/products/cheat-layer?utm_source=badge-top-post-badge&utm_medium=badge#cheat-layer


![image](https://github.com/OthersideAI/self-operating-computer/assets/11659839/bd186144-12ac-46de-a240-1bdc32f6fa7f)

**Comment by Bunger-Beesechurger** [comment]
@rohanarun 

Damn. Didn't know that it's been happening even earlier than that. I don't see the calling them out part though. Still, I wish you good luck with your work if this is plagiarism. At this point, since this is already open sourced, it's going to be tough

**Comment by alm0ra** [comment]
@rohanarun make your repo open source and we will also contribute to it :)) 
500 lines of shit code was your research it's wired.
It got 4k star because of YouTubers . And they also introduce this library for more view , AI is trend :)) 
More view more money.

**Comment by James4Ever0** [comment]
It doesn't matter. We know we have created a monster. Only the most determined can witness this very moment.

**Comment by CheatLayer** [comment]
> very

I wish you good luck, but you won't win this race with hard coded clicks. 

We're open sourcing an entire desktop application that actually works in Windows/Mac/Linux, and generalized agents using a new multi-modal model we trained to get precise clicks. Our Google demo uses a state machine and probabilities to solve it in a generalized way, but we have many more complex examples now that are mind blowing, including generating products. We didn't steal our research, and we'd be happy to share our significant progress with anyone interested in joining us. If you're truly interested in this idea, we're the bootstrapped startup that started during the pandemic to help everyone who was suffering rebuild online. This appears to be a well funded company ripping off startups and open source devs to do the work for them.

**Comment by lueluelue2006** [comment]
Where can I use Atlas-1 or Atlas-2？

**Comment by MoAbbasid** [comment]
here after their new scam lol

**Comment by showgood163** [comment]
Maybe more people should check this out after the reflection thing.

**Comment by humanely** [comment]
Atlas-1 never became OSS.
