### ISSUE TITLE
Windows 11 installation issue: Poetry could not find a pyproject.toml file in *path*\self-operating-computer or its parents

### ISSUE THREAD

**Issue by Jpups** [OthersideAI/self-operating-computer#77]
Trying to install SOC on Windows 11.

I get to the part where it says:

cat requirements.txt | xargs poetry add

This of course won't work on Windows so I used "@(cat requirements.txt) | %{&poetry add $_}" in Powershell, but I get the error mentioned in the title:

"Poetry could not find a pyproject.toml file in..."

Also tried: poetry add *depency-name* by copypasting the dependency name from requirements.txt but I get the same error.

Ideas anyone? Now that I'm thinking I might running too new a version of Poetry, but not sure

**Comment by michaelhhogue** [comment]
I believe @klxu03 added Poetry support. Can you look into this?

**Comment by Jpups** [comment]
I simply skipped the Poetry step since I noticed there were two steps labelled "3." and managed to get the installation working, except now I probably have to pay some money since I get the following error message:

Error parsing JSON: Error code: 404 - {'error': {'message': 'The model `gpt-4-vision-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

My key is correct since if I input the wrong key it complains about it explicitly.

**Comment by klxu03** [comment]
> I believe @klxu03 added Poetry support. Can you look into this?

i ended up deleting poetry since it seemed to cause issues for non-poetry to some people. and my apologies, those instructions in the README were for if you wanted to manually add poetry support yourself. ill probably just delete those lines from the README rq

**Comment by michaelhhogue** [comment]
@klxu03 Okay. Yeah that should probably be removed as it could cause confusion for non-poetry users. I'll leave this issue opened until it's removed as a reminder.

**Comment by klxu03** [comment]
> @klxu03 Okay. Yeah that should probably be removed as it could cause confusion for non-poetry users. I'll leave this issue opened until it's removed as a reminder.

https://github.com/OthersideAI/self-operating-computer/pull/70 okay yeah, deleted from README in my latest PR as well

**Comment by joshbickett** [comment]
Wanted to confirm, a poetry PR would be great. Sorry getting caught a little behind on reviewing PRs. Hopefully I'm not holding anything up!
