### ISSUE TITLE
Use Code Models For More Precise DOM Navigation

### ISSUE THREAD

**Issue by slavakurilyak** [OthersideAI/self-operating-computer#78]
Consider adding coding models like GPT-4 Turbo (128K token limit) to better navigate HTML DOM using [playwright](https://github.com/microsoft/playwright) by @microsoft. See similar implementation here: [BrowserGPT](https://github.com/mayt/BrowserGPT/) by @mayt.

**Comment by michaelhhogue** [comment]
@slavakurilyak Thanks for the suggestion! Feel free to join the Discord server mentioned in the README if you'd like to discuss this further.
