### ISSUE TITLE
Request timed out.

### ISSUE THREAD

**Issue by dockercore** [OthersideAI/self-operating-computer#79]
Error parsing JSON: Request timed out.
[Self-Operating Computer][Error] something went wrong :(
[Self-Operating Computer][Error] AI response
Failed take action after looking at the screenshot

**Comment by TedLau** [comment]
same issue, MacOSl.

**Comment by fr0g-66723067** [comment]
fix is here: https://github.com/OthersideAI/self-operating-computer/issues/80#issuecomment-1840423133

**Comment by fr0g-66723067** [comment]
are you able to hit the openai api url? 
```
curl https://api.openai.com/v1
```

**Comment by michaelhhogue** [comment]
@dockercore Sounds like an API issue. Can you verify if you're still having this problem?

**Comment by dockercore** [comment]
> are you able to hit the openai api url?
> 
> ```
> curl https://api.openai.com/v1
> ```

curl https://api.openai.com/v1
{
  "error": {
    "message": "Invalid URL (GET /v1)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

**Comment by joshbickett** [comment]
There've been some api outages with `gpt-4-vision` over the last few days. This may be related

**Comment by michaelhhogue** [comment]
@Sameeraali835 I mean to just try running ```operate``` again and see if there is still a "Request timed out" message. However, as @joshbickett mentioned, this is likely an issue on OpenAI's side with outages.

**Comment by YadocsAi** [comment]
Hello

Seams like I'm having the same trouble.
Here is the same I get from the curl command :
curl https://api.openai.com/v1
{
   "еггог": {
	"type": "invalid_request_error",
		"code": "unknown_url"
		"message": "Unknown request URL: GET /v1. Please check the UR L for typos, or see the docs at https://			platform.openai.com/docs/api-reference/."
		"param": null
	}
}

I have read request #79 and #80 to figure out what to do but nothing worked. Also made some double check about the API key letter format but it is the correct one as I use it with other tools.

Have you been able to figure out how to solve this issue ?

Thanks !
