### ISSUE TITLE
Error parsing JSON: Connection error.

### ISSUE THREAD

**Issue by NETJET21** [OthersideAI/self-operating-computer#87]
I obtained this image when running the command prompt with instructions, I'm using a windows system and I've adjusted for the adequate command prompts when following the quick-start guide, is there a way to allow permissions to the windows settings to screen record, or is automatically allowed, also, if I've already paid the 5 dlls in the billing section, I should have access to gpt-4-vision-preview through there right? Thank you, and great project! 
![Error parsing JSO](https://github.com/OthersideAI/self-operating-computer/assets/131493910/99e183e1-ee64-4dc6-887d-bad9a97b6a2e)

These are the commands that I followed, if you have any suggestions I'd appreciate it, thank you

git clone https://github.com/OthersideAI/self-operating-computer.git

cd self-operating-computer
conda create -n soc python=3.11
conda activate soc
where python
Users\username\Conda\envs\soc\python.exe -m pip install -r requirements.txt

(Opened a new command window)

cd self-operating-computer
conda activate soc
where python
\Users\username\Conda\envs\soc\python.exe -m pip install .
move .example.env .env
set OPENAI_API_KEY="my key from openai API keys"
operate

**Comment by michaelhhogue** [comment]
@NETJET21 There was an outage for ```gpt-4-vision-preview``` earlier. Are you still getting a connection error?

**Comment by NETJET21** [comment]
![image](https://github.com/OthersideAI/self-operating-computer/assets/131493910/7c3ec2d7-0d87-4889-aa52-2b236e416c68)
Hi Michael, yes I'm still getting the same issue, is there a step that I could've followed wrong?

**Comment by michaelhhogue** [comment]
@NETJET21 Did you run 
```
pip install .
```
after installing the requirements?

**Comment by michaelhhogue** [comment]
@NETJET21 Going ahead and closing this. If you're still having the connection error after trying to run without conda, let me know and I'll reopen.
