### ISSUE TITLE
Add support for LiteLLM to support API base change.

### ISSUE THREAD

**Issue by haseeb-heaven** [OthersideAI/self-operating-computer#9]
### 🚀 **Refactor the code** and use LiteLLM to support API base change.
🌐 As of now, GPT-4 Vision is *expensive to use* and GPT-4 usage is high.
Let consumers use their own API base by making the following change:

# Example:
```python
import openai

# Set your custom API base URL
openai.api_base = "http://myproxy-gpt.com/chatcompletions"
```

 📈 This change ensures that you will receive more users and encourage more testing.
🧪 People will start testing it more often, which will ultimately contribute to
*improving this product*. 🛠️

**Comment by horw** [comment]
Hello @haseeb-heaven, I have created a pull request for this. Let the maintainer check it, and perhaps they will merge it.

**Comment by haseeb-heaven** [comment]
Thanks for the quick PR
