### ISSUE TITLE
Update README deployment instructions to call-out the resolution definition

### ISSUE THREAD

**Issue by AzorianMatt** [OthersideAI/self-operating-computer#92]
One thing that got me when initially deploying this app was not being aware of a need to adjust statically configured screen dimensions. It would be quite ideal to post instructions to the README file to call out this need.

I'm running a 4-monitor workstation in a 2x2 grid so this wreaked havoc initially. It actually still doesn't work right but I suspect it's because the increase of resolution to 1920x1080x4 creates a processing issue for the GPT 4 model currently. I have not actually tried this project (yet) in a single monitor environment at the standard 1920x1080.

Additionally, one may want to specifically call out not to keep screenshots open taken by the program. At one point, I had one monitor covered with the screenshot grid file which was then being snapped in future screenshots. I can only imagine that this scenario also wreaks havoc on the model's ability to process the grid appropriately when a grid becomes present within the grid!

**Comment by AzorianMatt** [comment]
@michaelhhogue good to know! I thought I had reviewed the current code well enough, but apparently I missed the override of this. On a brief scan, all references I found seemed to go back to this variable so I am assuming it is updated in place during execution?

**Comment by AzorianMatt** [comment]
@michaelhhogue welp, I'm a dumb dumb! :laughing: It was right there in front of me the whole time, and I even refactored that method obviously. I'm ready for my vacation now!

I don't have a Mac or Windows environment either so I can only help so much there as well. No way will I ever pay those prices for something that will tell me no and hold my hand!

**Comment by michaelhhogue** [comment]
@AzorianMatt I have a Windows VM (that's as close as I'm getting to Windows hah) so I can test there. I'm also noticing that there's no case for Windows in `capture_mini_screenshot_with_cursor`. 

Not sure if you're familiar with this function. Basically, in -accurate mode, a mini screenshot is taken right around the cursor to let the model fine-tune it's movement of the cursor.

**Comment by AzorianMatt** [comment]
@michaelhhogue that's a good idea. I had Windows VMs but I finally got rid of my servers so no longer. I suppose I could setup a VM on my desktop again if I had to.

I am familiar with that function but it hasn't seemingly yielded good results for me, likely because the percentage estimates are coming in way off on my 2x2 monitor grid. In fact, it would seem that the estimates are generally very close to the stated general assumption defined in the vision prompt. They do vary from that definition, but usually not by a lot. Am I making the right assumption to think that the massive increase in resolution is decreasing the accuracy of the model naturally?

**Comment by michaelhhogue** [comment]
@AzorianMatt If you use a VM, make sure you have it setup to control the host's cursor. Took me way too long to figure that one out -_-

Your assumption is probably right. I'm running a 3440x1440 Ultrawide and notice higher accuracy on my 1920x1080 laptop.

**Comment by AzorianMatt** [comment]
@michaelhhogue thank you! That one would have definitely wasted a good 30 - 60 minutes of my time!

Also thank you for pseudo-confirming that. It would make sense as I'm sure in limited preview, it was only meant to be used on the most vanilla scenario. I'll be eagerly awaiting your tweaks for better multi-monitor support!

**Comment by michaelhhogue** [comment]
@AzorianMatt Going ahead and closing this since the issue itself wasn't actually a problem. However, I'll definitely be referencing our convo on screen resolutions in the future.
