### ISSUE TITLE
Surpport for the thirdparty API？

### ISSUE THREAD

**Issue by yuganerfish** [OthersideAI/self-operating-computer#95]
As the title described,is there any plan to surpport the thirdparty api？

**Comment by joshbickett** [comment]
@yuganerfish thanks for the input. As @michaelhhogue we have issue #86 for adding more multimodal models. I encourage someone to submit a PR to do so! 

I'll close this issue for now as I understand this to be a duplicate. If you had something else in mind for this issue, let us know and we can reopen it. Thanks!
